import curses

GREY =      (1, 0, -1)
RED =       (2, 1, -1)
GREEN =     (3, 2, -1)
YELLOW =    (4, 3, -1)
BLUE =      (5, 4, -1)
PURPLE =    (6, 5, -1)
CYAN =      (7, 6, -1)
WHITE =     (8, 15, -1)

ALL = [GREY, RED, GREEN, YELLOW, BLUE, CYAN, PURPLE, WHITE]

DEFAULT = WHITE
DISABLED = GREY
ERROR = RED
SUCCESS = GREEN
PRESSABLE = GREEN
WARNING = YELLOW
DECORATOR = CYAN
ADVANCED = PURPLE

BIG_TITLE = YELLOW
IMPORTANT = YELLOW
SMALL_TITLE = CYAN

EDITING_VALUE = YELLOW
VALID_VALUE = GREEN
INVALID_EDITING_VALUE = YELLOW
INVALID_VALUE = RED
SUBMIT = SUCCESS

LINK = CYAN
ACCESSED_LINK = PURPLE
TITLE = YELLOW
