
UP = 'KEY_UP'
DOWN = 'KEY_DOWN'
LEFT = 'KEY_LEFT'
RIGHT = 'KEY_RIGHT'
BACKSPACE = ['KEY_BACKSPACE', '\b', '\x7f']
DELETE = 'DC'
ESC = chr(27)

ENTER = ['KEY_ENTER', '\n']
VERTICAL_ARROWS = [UP, DOWN]
HORIZONTAL_ARROWS = [LEFT, RIGHT]
ARROWS = VERTICAL_ARROWS + HORIZONTAL_ARROWS

INPUT_IGNORE = ENTER + VERTICAL_ARROWS + [ESC]
